baseURL = "https://www.friedpotato.in/"
languageCode = 'en-us'
title = 'FriedPotato'
tableOfContents = true
[outputs]
 home = ['html', 'rss']
  section = ['html', 'rss']

[markup]
  [markup.highlight]

    noClasses = false
    lineNumbersInTable = true


[markup.goldmark.renderer]
  unsafe= true
